[project]
name        = 'ecal_calibration'
version     = '0.0.1'
readme      = 'README.md'
dependencies= [
'dask',
'pandas',
'bokeh',
'mplhep',
'scipy',
'uproot',
'vector',
'numpy',
'torch',
'data_manipulation_utilities',
]

[project.optional-dependencies]
dev  = ['pytest']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
make_toy_decays ='ecal_calibration_scripts.make_toy_decays:main'

[tool.setuptools.package-data]
ecal_calibration_data=[
'*/*/*.yaml',
'*/*/*.json',
]

[tool.setuptools]
#script-files=['src/dmu_scripts/git/publish']
