[tool.poetry]
name        = 'ecal_calibration'
description = 'Project meant to apply offline corrections to electrons in LHCb'
version     = 'v0.0.0'
readme      = 'README.md'

[tool.poetry.dependencies]
python  = '>=3.10'
pandas  = '*'
bokeh   = '*'
tqdm    = '*'
mplhep  = '*'
scipy   = '*'
uproot  = '*'
vector  = '*'
pyarrow = '*'
numpy   = '*'
dask                        = {version = '*', extras=['distributed']} 
data-manipulation-utilities = {version = '*', allow-prereleases=true}

[tool.poetry.extras]
dev  = ['pytest']
ml   = ['torch']
# -----------------------------------------
# Setuptools
# -----------------------------------------
[project]
name        = 'ecal_calibration'
description = 'Project meant to apply offline corrections to electrons in LHCb'
readme      = 'README.md'
dynamic     = ['version']

[build-system]
requires = ['setuptools>=61', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
version_scheme = 'guess-next-dev'
local_scheme   = 'node-and-date'

[project.scripts]
make_toy_decays ='ecal_calibration_scripts.make_toy_decays:main'

[tool.setuptools.package-data]
ecal_calibration_data=[
'**/*.yaml',
'**/*.json',
'**/*.csv',
]

[tool.setuptools.packages.find]
where   = ['src']
