[project]
name            = 'ecal_calibration'
readme          = 'README.md'
requires-python = '>=3.10'
dependencies    = [
'dask',
'pandas',
'bokeh',
'tqdm',
'mplhep',
'scipy',
'uproot',
'vector',
'pyarrow',
'dask[distributed]',
'numpy',
'data-manipulation-utilities',
]

[build-system]
requires = ['setuptools>=61', 'setuptools_scm', 'wheel']
build-backend = 'setuptools.build_meta'

[tool.setuptools_scm]
version_scheme = 'guess-next-dev'
local_scheme   = 'node-and-date'

[project.optional-dependencies]
dev  = ['pytest']
ml   = ['torch']
ci   = ['data-manipulation-utilities @ git+ssh://git@gitlab.cern.ch:7999/rx_run3/ecal_calibration.git@master']

[tools.setuptools.packages.find]
where   = ['src']

[project.scripts]
make_toy_decays ='ecal_calibration_scripts.make_toy_decays:main'

[tool.setuptools.package-data]
ecal_calibration_data=[
'**/*.yaml',
'**/*.json',
'**/*.csv',
]

[tool.setuptools]
#script-files=['src/dmu_scripts/git/publish']
